apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: astrapay

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - app-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: astrapay-spring-boot
      app.kubernetes.io/component: backend
      app.kubernetes.io/managed-by: kustomize

images:
  - name: astrapay/spring-boot-external
    newTag: latest
