apiVersion: v1
kind: Secret
metadata:
  name: astrapay-secrets
  namespace: astrapay
type: Opaque
data:
  # Base64 encoded values
  # astrapay_password -> YXN0cmFwYXlfcGFzc3dvcmQ=
  # astrapay_user -> YXN0cmFwYXlfdXNlcg==
  postgres-password: YXN0cmFwYXlfcGFzc3dvcmQ=
  postgres-username: YXN0cmFwYXlfdXNlcg==
