#!/bin/bash

# Docker Desktop Kubernetes Deployment Script
# Generated by GitHub Actions CI/CD Pipeline

set -e

echo "🚀 Starting Docker Desktop Kubernetes Deployment..."

# Check prerequisites
echo "📋 Checking prerequisites..."
if ! command -v kubectl &> /dev/null; then
    echo "❌ kubectl is not installed. Please install kubectl first."
    exit 1
fi

if ! kubectl cluster-info &> /dev/null; then
    echo "❌ Cannot connect to Kubernetes cluster. Please ensure Docker Desktop Kubernetes is enabled."
    exit 1
fi

echo "✅ Prerequisites check passed"

# Apply Kubernetes resources
echo "🔧 Applying Kubernetes resources..."
kubectl apply -k k8s/

# Wait for deployments
echo "⏳ Waiting for deployments to be ready..."
kubectl rollout status deployment/astrapay-app -n astrapay --timeout=300s
kubectl rollout status deployment/postgres-deployment -n astrapay --timeout=300s
kubectl rollout status deployment/redis-deployment -n astrapay --timeout=300s

# Get deployment status
echo "📊 Deployment Status:"
kubectl get pods -n astrapay
kubectl get services -n astrapay

# Verify application is running
echo "🔍 Verifying application health..."
kubectl wait --for=condition=ready pod -l app=astrapay-app -n astrapay --timeout=300s

echo "✅ Deployment completed successfully!"
echo ""
echo "🌐 Access the application:"
echo "   Option 1: kubectl port-forward service/astrapay-service 8000:8000 -n astrapay"
echo "   Then open: http://localhost:8000"
echo ""
echo "   Option 2: Test endpoints directly:"
echo "   Health: kubectl exec -n astrapay deployment/astrapay-app -- curl http://localhost:8000/actuator/health"
echo "   Hello: kubectl exec -n astrapay deployment/astrapay-app -- curl 'http://localhost:8000/hello?name=DockerDesktop&description=Test'"
echo ""
echo "🎉 Happy coding!"
